export { default as homeReveal } from './homeReveal'
export { default as homeToPage } from './homeToPage'
export { default as skillReveal } from './skillReveal'
export { default as skillToPage } from './skillToPage'
export { default as aboutReveal } from './aboutReveal'
export { default as aboutToPage } from './aboutToPage'
export { default as projectReveal } from './projectReveal'
export { default as projectToPage } from './projectToPage'